// <auto-generated />
namespace QuanLyKho.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class them_conf_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_conf_account));
        
        string IMigrationMetadata.Id
        {
            get { return "202111291501091_them_conf_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
